### ISSUE TITLE
Criar o HTML e CSS das 12 telas existentes no bootstrap

### ISSUE THREAD

**Issue by victor4pinheiro** [Avengers042/screens-css#1]
Criar o site realizado em Bootstrap (https://github.com/Avengers042/screens-bootstrap) usando somente HTML e CSS.

**Comment by victor4pinheiro** [comment]
@Samuka0909 , qual o seu progresso? Vejo aqui no Git e não há nada contendo o seu nome.

**Comment by Samuka0909** [comment]
Ainda estou tentando entender como funciona. A ferramenta

Em seg, 29 de ago de 2022 11:09 PM, Victor Pinheiro <
***@***.***> escreveu:

**Comment by victor4pinheiro** [comment]
Poderia descrever melhor, @Samuka0909 ? Pois estou há dias tentando me comunicar contigo e sem nenhum retorno.
Nessa descrição, inclua:

- Ferramentas que está usando;
- Ferramentas que está aprendendo;
- Dificuldades que está tendo;
- Progresso geral;
- Estimativa de entrega.

**Comment by Samuka0909** [comment]
Eu não sei usar Github e estou tendo algumas dificuldades pois instalei o
visual Studio mas não lembro como coloca o arquivo versão nove para
progredir na criação

Em ter, 30 de ago de 2022 10:03 AM, Victor Pinheiro <
***@***.***> escreveu:

**Comment by victor4pinheiro** [comment]
@Samuka0909 , responda todas as perguntas, por favor.

**Comment by victor4pinheiro** [comment]
Avisando a geral: eu testei rebase e depois merge para conferir o comportamento e realmente polui menos, contudo, preciso encontrar uma forma de deixar mais rastreável e visível como é o Pull Request.
